apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
  namespace: php-fpm
  labels:
    app: php-fpm
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      nodePort: 32080
      targetPort: 80
  selector:
    app: php-fpm
