apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-fpm
  name: php-fpm-web
  namespace: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm-php-fpm
          image: php-fpm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: www-storage
              mountPath: /srv/app/
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: www-storage
              mountPath: /srv/app/
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: www-storage
          persistentVolumeClaim:
            claimName: php-fpm-pv-claim
        - name: nginx-config-volume
          configMap:
            name: php-fpm-nginx-config