apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-fpm-pv-volume
  namespace: php-fpm
  labels:
    app: mysql
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/php-fpm-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-fpm-pv-claim
  namespace: php-fpm
  labels:
    app: mysql
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi