kind: ConfigMap
apiVersion: v1
metadata:
  name: php-fpm-db-config
  namespace: php-fpm
  labels:
    app: php-fpm
data:
  databaseUrl: "mysql-service.mysql.svc.cluster.local:3306"
  databaseName: "BOOK_LIB"