apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
  labels:
    app: mysql
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 3306
      nodePort: 32306
      targetPort: 3306
  selector:
    app: mysql
